-- MySQL Script generated by MySQL Workbench
-- Fri Apr 29 14:03:11 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema DBTur_firm
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema DBTur_firm
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DBTur_firm` DEFAULT CHARACTER SET utf8 ;
USE `DBTur_firm` ;

-- -----------------------------------------------------
-- Table `DBTur_firm`.`TouristsInfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBTur_firm`.`TouristsInfo` (
  `idTouristsInfo` INT NOT NULL,
  `PassportSeries` VARCHAR(45) NULL,
  `City` VARCHAR(45) NULL,
  `Country` VARCHAR(45) NULL,
  `PhoneNumber` INT NULL,
  `Index` INT NULL,
  PRIMARY KEY (`idTouristsInfo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBTur_firm`.`Tourists`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBTur_firm`.`Tourists` (
  `idTourists` INT NOT NULL,
  `TouristsLastName` VARCHAR(45) NULL,
  `TouristsFirstName` VARCHAR(45) NULL,
  `TouristsMidleName` VARCHAR(45) NULL,
  `TouristsInfo_idTouristsInfo` INT NOT NULL,
  PRIMARY KEY (`idTourists`),
    FOREIGN KEY (`idTouristsInfo`)
    REFERENCES `DBTur_firm`.`TouristsInfo` (`idTouristsInfo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBTur_firm`.`Tours`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBTur_firm`.`Tours` (
  `idTours` INT NOT NULL,
  `TourName` VARCHAR(45) NULL,
  `TourPrice` INT NULL,
  `TourInfo` LONGTEXT NULL,
  PRIMARY KEY (`idTours`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBTur_firm`.`Seasons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBTur_firm`.`Seasons` (
  `idSeason` INT NOT NULL,
  `SeasonDateStart` DATE NULL,
  `SeasonDateEnd` DATE NULL,
  `SeasonClose` TINYINT NULL,
  `Tours_idTours` INT NOT NULL,
  PRIMARY KEY (`idSeason`),
    FOREIGN KEY (`idTours`)
    REFERENCES `DBTur_firm`.`Tours` (`idTours`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBTur_firm`.`vouchers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBTur_firm`.`vouchers` (
  `idvoucher` INT NOT NULL,
  `TouristsInfo_idTourists` INT NOT NULL,
  `Seasons_idSeason` INT NOT NULL,
  PRIMARY KEY (`idvoucher`),
    FOREIGN KEY (`idTourists`)
    REFERENCES `DBTur_firm`.`TouristsInfo` (`idTouristsInfo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    FOREIGN KEY (`idSeason`)
    REFERENCES `DBTur_firm`.`Seasons` (`idSeason`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBTur_firm`.`Payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBTur_firm`.`Payment` (
  `idPayment` INT NOT NULL,
  `PaymentDate` DATE NULL,
  `PaymentCost` INT NULL,
  `vouchers_idvoucher` INT NOT NULL,
  PRIMARY KEY (`idPayment`),
    FOREIGN KEY (`idvoucher`)
    REFERENCES `DBTur_firm`.`vouchers` (`idvoucher`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
